name: Déploiement GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Déploiement sur GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload des fichiers
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Publication sur GitHub Pages
        uses: actions/deploy-pages@v4
